# Generated by Django 3.1.2 on 2022-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('courseID', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('grade', models.FloatField()),
            ],
        ),
    ]
