# Generated by Django 3.1.2 on 2022-04-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cTracker', '0002_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
