# Generated by Django 3.1.2 on 2022-04-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cTracker', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='studentID',
        ),
        migrations.AddField(
            model_name='enrolled',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cTracker.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cTracker.student'),
            preserve_default=False,
        ),
    ]
